#!/bin/sh
#
# /init executable file in the initramfs 
#

mount -t devtmpfs dev /dev
mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t securityfs securityfs /sys/kernel/security

exec /sbin/getty -n -l /bin/sh 115200 /dev/console

/sbin/poweroff -f